from enum import Enum


class SemanticType(Enum):
    NUMERIC_CONTINUOUS = "NUMERIC_CONTINUOUS"
    NUMERIC_DISCRETE = "NUMERIC_DISCRETE"
    CATEGORICAL = "CATEGORICAL"
    HIGH_CARDINALITY = "HIGH_CARDINALITY"
    BOOLEAN = "BOOLEAN"
    DATE = "DATE"
    DATETIME = "DATETIME"
    EMAIL = "EMAIL"
    PHONE = "PHONE"
    ID_CANDIDATE = "ID_CANDIDATE"
    MIXED = "MIXED"
    EMPTY = "EMPTY"
    CONSTANT = "CONSTANT"
